version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - NODE_ENV
        - PORT
        - DB_NAME
        - DB_USER
        - DB_HOST
        - DB_PASSWORD
        - DB_PORT
        - GOOGLE_CLOUD_API_KEY
        - JWT_SECRET
        - SESSION_SECRET
        - GOOGLE_CLOUD_ID
        - GOOGLE_CLIENT_ID
        - GOOGLE_CLIENT_SECRET
        - OPENAI_API_KEY
        - REDIS_SECRET
        - REDIS_HOST
        - REDIS_PORT
        - PAT
        - USER_ID
        - APP_ID
        - MODEL_ID
        - TEXT_MODEL_USER_ID
        - TEXT_MODEL_APP_ID
        - TEXT_MODEL_VERSION_ID
        - TEXT_MODEL_ID
        - MODEL_VERSION_ID
        - CLOUDINARY_NAME
        - CLOUDINARY_API_KEY
        - CLOUDINARY_API_SECRET
        - DATABASE_URL
        - AZURE_ACCOUNT_NAME
        - AZURE_ACCOUNT_KEY
        - AZURE_CONTAINER_NAME
        - SPEECH_KEY
        - SPEECH_REGION
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && yarn build && yarn start"
